spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mq_consumer?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 100
    initialSize: 10
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

mybatis:
  mapperLocations: classpath*:com/wz/mapper/*.xml
  typeAliasesPackage: com.wz.model

server:
  port: 9009