job:
  zkConfig:
    zkConnectString: 127.0.0.1:2181
    rootPath: /taobao-pamirs-schedule/huijin
    zkSessionTimeout: 60000
    userName: ScheduleAdmin
    password: password
    isCheckParentPath: true